In [ ]:
##Matrix operations (using vectorization) and transformation using python and SVD using Python.

In [1]:
import numpy as np;

list1=[10,20,30,40]
np.array(list1)

array([10, 20, 30, 40])

In [2]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
np.random.rand(5)

array([0.92171761, 0.03415274, 0.37160351, 0.92412132, 0.17348446])

In [13]:
np.random.rand(5,4)

array([[0.95639916, 0.31397122, 0.62603887, 0.64725876],
       [0.21901087, 0.62762523, 0.99615481, 0.01631249],
       [0.07093052, 0.58072413, 0.90699777, 0.64703834],
       [0.68076642, 0.16781397, 0.8777742 , 0.10452591],
       [0.95417176, 0.98608712, 0.68668034, 0.54030757]])

In [14]:
np.random.randn(5)

array([-0.33977399,  0.75481973, -0.13820242,  0.51174675, -1.41193213])

In [15]:
np.random.randint(1,100)

13

In [16]:
np.random.randint(1,100,2)

array([67, 53])

In [17]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
np.random.randint(0,50,10)

array([13,  1, 10, 17, 13,  1, 11, 25,  4, 37])

In [19]:
a=np.arange(0,25)

In [20]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
a.max()

24

In [24]:
a.min()

0

In [25]:
a.argmax()

24

In [26]:
a.argmin()

0

In [27]:
a.shape

(25,)

In [28]:
a.dtype

dtype('int64')

In [29]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l=np.array(l)

In [30]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
l[2]

array([7, 8, 9])

In [32]:
l[1,2]

6

In [34]:
lis=[10,20,30,40]
t=np.array(lis)
t

array([10, 20, 30, 40])

In [35]:
t[0:3]=100

In [36]:
t

array([100, 100, 100,  40])

In [37]:
l[1:2]=100

In [38]:
l

array([[  1,   2,   3],
       [100, 100, 100],
       [  7,   8,   9]])

In [39]:
l[:]=50

In [40]:
l

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [42]:
e=[[5,10,15],[20,25,30],[35,40,45]]
y=np.array(e)
y

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
y[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
y[1:3,0:2]

array([[20, 25],
       [35, 40]])

In [47]:
lt=[[10,20,30],[35,40,45],[60,65,80]]
c=np.array(lt)
c

array([[10, 20, 30],
       [35, 40, 45],
       [60, 65, 80]])

In [48]:
tf=c>20
c[tf]

array([30, 35, 40, 45, 60, 65, 80])

In [49]:
import numpy as np
s=np.arange(0,10)
s+s 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
s=np.arange(0,10)
s-s 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
s=np.arange(0,10)
s*s 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [52]:
s=np.arange(0,10)
s/s 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
s=np.ones(10)
s*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [58]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [59]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [60]:
import numpy as np
m=np.arange(0,9)
m.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.random.rand(1)

array([0.28159462])

In [63]:
np.random.rand(1,100,25)

array([[[0.87445312, 0.71165176, 0.3358876 , ..., 0.28494299,
         0.3936704 , 0.08957892],
        [0.59182691, 0.07858375, 0.16304391, ..., 0.21107437,
         0.27025942, 0.81111278],
        [0.73061166, 0.02934415, 0.04198986, ..., 0.09335635,
         0.64824907, 0.50019437],
        ...,
        [0.24234321, 0.82538448, 0.13358496, ..., 0.97329188,
         0.03431887, 0.89912926],
        [0.64006037, 0.95758533, 0.23033654, ..., 0.57628873,
         0.98910826, 0.69687078],
        [0.2030761 , 0.75376513, 0.85972704, ..., 0.2597019 ,
         0.0600154 , 0.39157981]]])

In [64]:
np.random.randn(5,5)

array([[ 0.24013772,  0.82909518,  0.22862026,  1.60535486,  1.28124568],
       [ 0.02554269, -0.17290592, -0.06595962, -0.05082622, -1.34420903],
       [-0.66031274, -1.2281319 , -0.09929577, -0.81961654, -0.54088693],
       [-0.4490737 , -0.96847067,  2.1901552 , -0.19751864,  0.95745089],
       [-0.70955408,  0.31568932, -0.13393278,  0.1615628 , -1.76491618]])

In [65]:
c=np.arange(1,101)
f=c.reshape(10,10)
f/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [66]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [67]:
d=np.arange(1,26).reshape(5,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [68]:
d[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [69]:
d[3][4]

20

In [70]:
d[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [71]:
d[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
d[4:]

array([[21, 22, 23, 24, 25]])

In [73]:
d.sum()

325

In [74]:
d.std()

7.211102550927978

**SVM**

In [75]:
import numpy as np
from scipy.linalg import svd
l1=[[10,20],[40,50],[70,80]]
x=np.array(l1).reshape(3,2)
print(x)
print("\n")
u,s,vt=svd(x)
print(u)
print("\n")
print(s)
print("\n")
print(vt)

[[10 20]
 [40 50]
 [70 80]]


[[-0.17259857  0.89640564  0.40824829]
 [-0.50818671  0.27400657 -0.81649658]
 [-0.84377485 -0.3483925   0.40824829]]


[125.96017181   5.83396253]


[[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [76]:
u,s,vt=svd(x,full_matrices=True)
print(u)
print("\n")
print(s)
print("\n")
print(vt)

[[-0.17259857  0.89640564  0.40824829]
 [-0.50818671  0.27400657 -0.81649658]
 [-0.84377485 -0.3483925   0.40824829]]


[125.96017181   5.83396253]


[[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [77]:
u,s,vt=svd(x,full_matrices=False)
print(u)
print("\n")
print(s)
print("\n")
print(vt)

[[-0.17259857  0.89640564]
 [-0.50818671  0.27400657]
 [-0.84377485 -0.3483925 ]]


[125.96017181   5.83396253]


[[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [78]:
# Return the original matrix X
# @ is used for matrix multiplication in Py3, use np.matmul with Py2
Y=(u @ np.diag(s) @ vt)
Y 

array([[10., 20.],
       [40., 50.],
       [70., 80.]])