In [2]:
#Matrix operations (using vectorization) and transformation using python and SVD using Python.
import numpy as np;

list1=[10,20,30,40]
np.array(list1)

list2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list2)
np.arange(0,10)
np.arange(0,10,2)
np.zeros(3)
np.zeros((5,5))
np.ones(3)
np.ones((3,3))
np.eye(3)
np.linspace(0,5,10)
np.linspace(0,10,100)
np.random.rand(5)
np.random.rand(5,4)
np.random.randn(5)
np.random.randint(1,100)
np.random.randint(1,100,2)
np.arange(0,25)
np.random.randint(0,50,10)

a=np.arange(0,25)
a.reshape(5,5)
a.max()
a.min()
a.argmax()
a.argmin()
a.shape
a.dtype

l=[[1,2,3],[4,5,6],[7,8,9]]
l=np.array(l)
l[2]
l[1,2]
lis=[10,20,30,40]
t=np.array(lis)
t[0:3]=100

l[1:2]=100
# print(l)
l[:]=50
# print(l)

e=[[5,10,15],[20,25,30],[35,40,45]]
y=np.array(e)
y[:2,1:]
y[1:3,0:2]

lt=[[10,20,30],[35,40,45],[60,65,80]]
c=np.array(lt)
tf=c>20
c[tf]




array([30, 35, 40, 45, 60, 65, 80])

In [3]:
import numpy as np
s=np.arange(0,10)
s+s 

s=np.arange(0,10)
s-s 

s=np.arange(0,10)
s*s 

s=np.arange(0,10)
s/s 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [4]:
import numpy as np
np.zeros(10)
np.ones(10)
s=np.ones(10)
s*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
import numpy as np
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
import numpy as np
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
import numpy as np
m=np.arange(0,9)
m.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
import numpy as np
np.random.rand(1)

array([0.63013506])

In [10]:
np.random.rand(1,100,25)

array([[[0.56232949, 0.68423231, 0.70725517, ..., 0.56396312,
         0.78280128, 0.6233969 ],
        [0.38611727, 0.20871148, 0.90914758, ..., 0.09061035,
         0.8611587 , 0.20961606],
        [0.40314273, 0.989946  , 0.37462092, ..., 0.40751528,
         0.18083719, 0.99702374],
        ...,
        [0.4583213 , 0.71987921, 0.48255414, ..., 0.84123357,
         0.03470449, 0.03957747],
        [0.92176842, 0.25913381, 0.9855556 , ..., 0.27028941,
         0.88955043, 0.83687567],
        [0.10088976, 0.48728482, 0.22128749, ..., 0.32358756,
         0.20865605, 0.05883834]]])

In [11]:
np.random.randn(5,5)

array([[ 1.28324546, -0.72440023, -2.16779651, -0.05225372,  0.74506449],
       [-1.77343959,  0.26335886, -0.8644148 ,  0.22499591, -0.59366922],
       [-1.36265406,  0.75593928,  0.21080699, -1.21459483,  0.62410261],
       [-1.67471662,  0.585262  , -0.44907367,  0.3274141 , -0.12240634],
       [-0.52379635,  1.14919921,  0.43310748,  1.80185016, -1.75051451]])

In [12]:
c=np.arange(1,101)
f=c.reshape(10,10)
f/100


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
d=np.arange(1,26).reshape(5,5)
d
# d[2:,1:]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
d[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
d[3][4]

20

In [17]:
d[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
d[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
d[4:]

array([[21, 22, 23, 24, 25]])

In [20]:
d.sum()

325

In [21]:
d.std()


7.211102550927978

**SVD**

In [22]:
import numpy as np
from scipy.linalg import svd
l1=[[10,20],[40,50],[70,80]]
x=np.array(l1).reshape(3,2)
print(x)
print("\n")
u,s,vt=svd(x)
print(u)
print("\n")
print(s)
print("\n")
print(vt)



[[10 20]
 [40 50]
 [70 80]]


[[-0.17259857  0.89640564  0.40824829]
 [-0.50818671  0.27400657 -0.81649658]
 [-0.84377485 -0.3483925   0.40824829]]


[125.96017181   5.83396253]


[[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [23]:
u,s,vt=svd(x,full_matrices=True)
print(u)
print("\n")
print(s)
print("\n")
print(vt)

[[-0.17259857  0.89640564  0.40824829]
 [-0.50818671  0.27400657 -0.81649658]
 [-0.84377485 -0.3483925   0.40824829]]


[125.96017181   5.83396253]


[[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [24]:
u,s,vt=svd(x,full_matrices=False)
print(u)
print("\n")
print(s)
print("\n")
print(vt)

[[-0.17259857  0.89640564]
 [-0.50818671  0.27400657]
 [-0.84377485 -0.3483925 ]]


[125.96017181   5.83396253]


[[-0.64399479 -0.76502988]
 [-0.76502988  0.64399479]]


In [25]:
# Return the original matrix X
# @ is used for matrix multiplication in Py3, use np.matmul with Py2
Y=(u @ np.diag(s) @ vt)
Y 

array([[10., 20.],
       [40., 50.],
       [70., 80.]])